"""empty message

Revision ID: 0f601b0993c7
Revises: 95b9eeffb6fa
Create Date: 2024-04-21 10:15:53.272804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f601b0993c7'
down_revision = '95b9eeffb6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('food_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('openingHours', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('img_1_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('img_2_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('img_3_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('img_3_url')
        batch_op.drop_column('img_2_url')
        batch_op.drop_column('img_1_url')
        batch_op.drop_column('openingHours')
        batch_op.drop_column('food_type')
        batch_op.drop_column('call')

    # ### end Alembic commands ###
