"""empty message

Revision ID: 29ad1ce170cd
Revises: 2294c79341b3
Create Date: 2024-04-27 00:40:04.949629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ad1ce170cd'
down_revision = '2294c79341b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('restaurant_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['restaurant_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('restaurant_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
