"""empty message

Revision ID: 64eef256cae6
Revises: ea9a6ee39d83
Create Date: 2024-04-20 00:31:18.379744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64eef256cae6'
down_revision = 'ea9a6ee39d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('price_range', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('hours', sa.String(), nullable=True))
        batch_op.alter_column('address_link',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('address_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('hours')
        batch_op.drop_column('city')
        batch_op.drop_column('price_range')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
