"""empty message

Revision ID: 71246d84cbfe
Revises: f417357ea337
Create Date: 2024-04-02 00:16:46.133967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71246d84cbfe'
down_revision = 'f417357ea337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(), nullable=False),
    sa.Column('restaurant_phone', sa.Integer(), nullable=False),
    sa.Column('address_link', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_register_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_foreign_key(None, 'user_register', ['user_register_id'], ['id'])
        batch_op.drop_column('email')
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('user_register_id')

    op.drop_table('restaurant')
    op.drop_table('user_register')
    # ### end Alembic commands ###
