"""empty message

Revision ID: 783d41eb3e65
Revises: 29ad1ce170cd
Create Date: 2024-04-29 16:58:50.055988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783d41eb3e65'
down_revision = '29ad1ce170cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_constraint('restaurant_restaurant_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.create_unique_constraint('restaurant_restaurant_name_key', ['restaurant_name'])

    # ### end Alembic commands ###
