import click
import json
from api.models import db, Restaurant

"""
In this file, you can add as many commands as you want using the @app.cli.command decorator
Flask commands are usefull to run cronjobs or tasks outside of the API but still in integration 
with youy database, for example: Import the price of bitcoin every night as 12am
"""
def setup_commands(app):


    @app.cli.command("populate-restaurant-table")
    def generate_restaurant_list():
        restaurant_list = [
            {
                "id": "0",
                "restaurant_name": "Seasoned Vegan Real Quick",
                "call": "+12122220092",
                "restaurant_phone": "(212) 222-0092",
                "address": "128 2nd Ave, New York, NY",
                "address_link": "https://maps.app.goo.gl/WKmxAjvS3RqEaUv78",
                "rating": "4.4 ★★★★",
                "food_type": "Vegan",
                "price_range" : "$$",
                "url" : "https://www.seasonedvegan.com/",
                "user_register_id" : "",
                "city": "NYC",
                "openingHours": [{"days": "MON - THURS", "hours": "11AM - 12AM"}, {"days": "FRI - SAT", "hours":"11AM - 3AM"}, {"days": "SUN", "hours": "11AM - 12AM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/1blQSQRt42H_dFj-n9uKww/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/-cB1VBHZjiz5y2S8Z20o1A/o.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/-OVLSGBt7l-0mX1KAzILhQ/o.jpg"
            },
            {
                "id": "1",
                "restaurant_name": "Avant Garden",
                "call": "+18333284588",
                "restaurant_phone": "(833) 328-4588",
                "address": "95 Avenue A, New York, NY",
                "address_link": "https://maps.app.goo.gl/LhpYNWKNe4fdiiKC7",
                "rating": "4.6 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$$$",
                "url" : "https://www.avantgardennyc.com/",
                "user_register_id" : "",
                "city": "NYC",
                "openingHours": [{"days": "MON - SUN", "hours": "5PM - 11PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/0DTlNsBy9zXYsgM9nTLv-Q/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/mtTSFyrs6ouHoenIJp37CQ/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/rsEuUYKgoeBVyoJwVXULcg/348s.jpg"
            },
            {
                "id": "2",
                "restaurant_name": "Ladybird",
                "call": "+18333284588",
                "restaurant_phone": "(833) 328-4588, ext. 702",
                "address": "111 E 7th St, New York, NY",
                "address_link": "https://maps.app.goo.gl/Kwbvh5ekBz8Hij8U8",
                "rating": "4.5 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$$",
                "url" : "https://www.ladybirdny.com/",
                "user_register_id" : "",
                "city": "NYC",
                "openingHours": [{"days": "MON - THURS", "hours": "5PM - 10PM"}, {"days": "FRI", "hours": "5PM - 11PM"}, {"days": "SAT", "hours": "11AM - 3:30PM & 5PM - 11PM"}, {"days": "SUN", "hours": "11AM - 3:30PM & 5PM - 10PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/PbE5gzg5Lnsk1wNjPTaD0A/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/RZAaB5_HLubbzJt1nbk3dw/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/91C-1ukXmeAlObM5shgeaA/348s.jpg"
            },
            {
                "id": "3",
                "restaurant_name": "Willow Vegan Bistro",
                "call": "+12129292889",
                "restaurant_phone": "(212) 929-2889",
                "address": "199 8th Ave, New York, NY",
                "address_link": "https://maps.app.goo.gl/4SEfDXUo6CfQX2Ag8",
                "rating": "4.6 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$$",
                "url" : "https://willownewyork.com/",
                "user_register_id" : "",
                "city": "NYC",
                "openingHours": [{"days": "MON - THURS", "hours": "4:30PM - 10:30PM"}, {"days": "FRI", "hours": "4:30PM - 11:30PM"}, {"days": "SAT", "hours": "11:30AM - 11:30PM"}, {"days": "SUN", "hours": "11:30AM - 10:30PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/89GYFC9ngYInp2LgJ48mig/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/e_5Oe3kkSthT0K0OsUR_CA/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/7DEcwWPetpgnCm8qKwrYEQ/348s.jpg"
            },
            {
                "id": "4",
                "restaurant_name": "Planta Queen",
                "call": "+19176757700",
                "restaurant_phone": "(917) 675-7700",
                "address": "15 W 27th St, New York, NY",
                "address_link": "https://maps.app.goo.gl/T2aoA1DxPUT7Smv96",
                "rating": "4.6 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$$",
                "url" : "https://www.plantarestaurants.com/location/planta-queen-new-york-city/",
                "user_register_id" : "",
                "city": "NYC",
                "openingHours": [{"days": "MON - THURS", "hours": "11:30AM - 10PM"}, {"days": "FRI", "hours": "11:30AM - 11PM"}, {"days": "SAT", "hours": "11AM - 11PM"}, {"days": "SUN", "hours": "11AM - 10PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/y8gPWgjFxyRc6wxrWPm4wg/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/rkDDGIJKqToCXOltud6CFA/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/hOVOpRVSW3T_I1lQ8SQ4Bg/348s.jpg"
            },
            {
                "id": "5",
                "restaurant_name": "Le Botaniste",
                "call": "+16464522555",
                "restaurant_phone": "(646) 452-2555",
                "address": "833 Lexington Ave, New York, NY",
                "address_link": "https://maps.app.goo.gl/nMkGq4jLBvLTY8P68",
                "rating": "4.7 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$",
                "url" : "https://lebotaniste.us/locations/",
                "user_register_id" : "",
                "city": "NYC",
                "openingHours": [{"days": "MON - SUN", "hours": "11AM - 9PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/4cE9Kj0hyvrhhonzPWJJxg/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/3rrAekLuKuyDYQm914diEw/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/ISRGmxk_EBN1qNtJRQr83w/348s.jpg"
            },
            {
                "id": "6",
                "restaurant_name": "Dirt Candy",
                "call": "+12122287732",
                "restaurant_phone": "(212) 228-7732",
                "address": "86 Allen St, New York, NY",
                "address_link": "https://maps.app.goo.gl/2b39aTccGuDSFfV89",
                "rating": "4.6 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$",
                "url" : "https://www.dirtcandynyc.com/hours-location",
                "user_register_id" : "",
                "city": "NYC",
                "openingHours": [{"days": "TUES - SAT", "hours": "5:30PM - 10:30PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/t2NSrjyRdYbD_5PZZ_Ly1g/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/wC0FBn-NrUzL5YecGUulLg/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/IZ8gOvpKDwqcViuY2X8G_w/348s.jpg"
            },
            {
                "id": "7",
                "restaurant_name": "Vegan On The Fly",
                "call": "+19172658242",
                "restaurant_phone": "(917) 265-8242",
                "address": "24 W 45th St, New York, NY",
                "address_link": "https://maps.app.goo.gl/pkwa1RTDtUmGmuDu5",
                "rating": "4.8 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$",
                "url" : "https://www.veganontf.com/",
                "user_register_id" : "",
                "city": "NYC",
                "openingHours": [{"days": "MON - SAT", "hours": "11AM - 7PM"}, {"days": "SUN", "hours": "11AM - 7PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/UA4luk0z-UWv7tzAOtetSw/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/sBlftAM36GPm-yzU-SR54g/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/RKdNsSTn62xZL4Ckmx36Mw/348s.jpg"
            },
            {
                "id": "8",
                "restaurant_name": "Blosson on Columbus",
                "call": "+12128752600",
                "restaurant_phone": "(212) 875-2600",
                "address": "507 Columbus Ave, New York, NY",
                "address_link": "https://maps.app.goo.gl/DuTkqW3CP2D8fXgA9",
                "rating": "4.4 ★★★★",
                "food_type": "Vegan",
                "price_range" : "$$",
                "url" : "https://www.blossomnyc.com/contact",
                "user_register_id" : "",
                "city": "NYC",
                "openingHours": [{"days": "MON - FRI", "hours": "11:30AM - 10PM"}, {"days": "SAT - SUN", "hours": "11AM - 10PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/hPCY682KqrmCP_puamgVqQ/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/dfanP-xoiygVoTRSsK9O8w/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/MvW5WzruTrq5JhTlDYlzQg/348s.jpg"
            },
        	# start of LA restaurants
            {
                "id": "9",
                "restaurant_name": "Vinh Loi Tofu",
                "call": "+15624033377",
                "restaurant_phone": "(562) 403-3377",
                "address": "11818 South St #101, Cerritos, CA 90703",
                "address_link": "https://maps.app.goo.gl/qxBcyaYzirHk6kZn9",
                "rating": "4.8 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$",
                "url" : "https://www.VinhLoiTofu.com/",
                "user_register_id" : "",
                "city": "LA",
                "openingHours": [{"days": "MON - SUN", "hours": "11AM - 8PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/12CGuy3lOs26WzcI-ELGiA/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/XKa68_rvb0ZeyCSavKptPA/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/Va59NcIjGFh9tld1v-6J-A/348s.jpg"
            },
            {
                "id": "10",
                "restaurant_name": "El Cocinero Restaurant",
                "call": "+18183868419",
                "restaurant_phone": "(818) 386-8419",
                "address": "6265 Sepulveda Blvd UNIT 12, Van Nuys, CA 91411",
                "address_link": "https://maps.app.goo.gl/YSJxstkeeU8rQN589",
                "rating": "4.7 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$",
                "url" : "https://www.elcocinerorestaurant.com/",
                "user_register_id" : "",
                "city": "LA",
                "openingHours": [{"days": "TUES - SUN", "hours": "1PM - 8PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/S13Wqs8YrkqZ1neVF2BvPg/o.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/umGLvy32NL1tA_EMN2X-Uw/o.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/SXlut467v8pubi8I0xHt3Q/o.jpg"
            },
            {
                "id": "11",
                "restaurant_name": "Toluca Bakery",
                "call": "+18186913169",
                "restaurant_phone": "(818) 691-3169",
                "address": "11365 Riverside Dr, Toluca Lake, California 91602",
                "address_link": "https://maps.app.goo.gl/yezPzXhuj3SiuJbr6",
                "rating": "4.8 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$",
                "url" : "https://www.facebook.com/tolucabakery",
                "user_register_id" : "",
                "city": "LA",
                "openingHours": [{"days": "MON - SAT", "hours": "8AM - 7:30PM"}, {"days": "SUN", "hours": "9AM - 6PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/fe-LYZUihM8MzgjbmeQD2w/o.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/O4cY7b4Xu-dh3KXjWhu88A/o.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/b4_23xZvFE1Pj9luO5onsg/o.jpg"
            },
            {
                "id": "12",
                "restaurant_name": "Crossroads Kitchen",
                "call": "+13237829245",
                "restaurant_phone": "(323) 782-9245",
                "address": "8284 Melrose Ave, Los Angeles, CA 90046",
                "address_link": "https://maps.app.goo.gl/zhKyqv4hVDWzo1Pq6",
                "rating": "4.6 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$$",
                "url" : "https://www.crossroadskitchen.com/",
                "user_register_id" : "",
                "city": "LA",
                "openingHours": [{"days": "MON - FRI", "hours": "11AM - 3PM & 5PM - 11PM"}, {"days": "SAT", "hours": "10AM - 3PM & 5PM - 11PM"}, {"days": "SUN", "hours": "10AM - 3PM & 5PM - 10PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/Iamb2OGgFlrseklcbL3UmA/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/BZ3N32Mxvoxn3Ku_5lYxuQ/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/k2DDehigI5tbI1Edt8L1fA/348s.jpg"
            },
            {
                "id": "13",
                "restaurant_name": "Rahel Ethiopian Vegan Cuisine",
                "call": "+13239378401",
                "restaurant_phone": "(323) 937-8401",
                "address": "1047 S Fairfax Ave, Los Angeles, CA 90019",
                "address_link": "https://maps.app.goo.gl/zwBUaZoiqJnVrjgx9",
                "rating": "4.7 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$",
                "url" : "https://rahelvegancuisine.com/",
                "user_register_id" : "",
                "city": "LA",
                "openingHours": [{"days": "TUES - THURS", "hours": "4PM - 10PM"}, {"days": "FRI - SUN", "hours": "11AM - 10PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/mGmtnakwu5RprvFeJ7D5OQ/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/7Xp11vgvTu1xjmFTBjaI8A/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/z56eAEJVP-UsGHukELjmkQ/348s.jpg"
            },
            {
                "id": "14",
                "restaurant_name": "Stuff I Eat",
                "call": "+13106710115",
                "restaurant_phone": "(310) 671-0115",
                "address": "114 N Market St, Inglewood, CA 90301",
                "address_link": "https://maps.app.goo.gl/1E2CZYK5Z3s3q3sbA",
                "rating": "4.7 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$",
                "url" : "https://www.stuffieat.com/",
                "user_register_id" : "",
                "city": "LA",
                "openingHours": [{"days": "WED - SUN", "hours": "12PM - 6PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/A6EDB8hoAkabQmj3k6F5Cg/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/FM3wwVA-3HZBULrHGVT7eg/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/xejbgsBtuqzfFvFLlCTz2w/348s.jpg"
            },
            {
                "id": "15",
                "restaurant_name": "Vegan AF Food Truck",
                "call": "+13233474970",
                "restaurant_phone": "(323) 347-4970",
                "address": "Check Social Media for the Latest Location!",
                "address_link": "https://www.facebook.com/profile.php?id=100083618472256",
                "rating": "4.4 ★★★★",
                "food_type": "Vegan",
                "price_range" : "$$",
                "url" : "https://www.facebook.com/profile.php?id=100083618472256",
                "user_register_id" : "",
                "city": "LA",
                "openingHours": [{"days": "THURS - SUN", "hours": "(Check Social Media for location & hours)"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/Qifi95WaBgAdoObIaR3Ckg/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/_FbsSBibFlnU1TNLNsm9dg/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/Yw_OtMn5FtZmp_f46Z1MmA/348s.jpg"
            },
            {
                "id": "16",
                "restaurant_name": "Bulan Thai Vegetarian Kitchen",
                "call": "+13239131488",
                "restaurant_phone": "(323) 913-1488",
                "address": "4114 Santa Monica Blvd, Los Angeles, CA 90029",
                "address_link": "https://maps.app.goo.gl/mKgr16WSfKSeVGyD6",
                "rating": "4.7 ★★★★★",
                "food_type": "Vegan",
                "price_range" : "$$",
                "url" : "https://www.bulanthaikitchen.com/",
                "user_register_id" : "",
                "city": "LA",
                "openingHours": [{"days": "MON - SUN", "hours": "11:30AM - 9PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/BjTQT3eTWWib0tyoqqrXog/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/b4lPjrRw_bhNjFTkKWLiug/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/Z7tPFuee1SSBM2jQbmp-AQ/348s.jpg"
            },
            {
                "id": "17",
                "restaurant_name": "De Buena Planta Silver Lake",
                "call": "+13234269023",
                "restaurant_phone": "(323) 426-9023",
                "address": "2815 W Sunset Blvd, Los Angeles, CA 90026",
                "address_link": "https://maps.app.goo.gl/TK6zSwasHX6ZFBXP7",
                "rating": "4.3 ★★★★",
                "food_type": "Vegan",
                "price_range" : "$$",
                "url" : "https://www.debuenaplanta.us/",
                "user_register_id" : "",
                "city": "LA",
                "openingHours": [{"days": "WED - THURS", "hours": "4PM - 10PM"}, {"days": "FRI - SAT", "hours": "4PM - 12AM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/fkfb9eJeNXJ0LZcXvYmYog/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/oShZnHvatCKOmuzJoPURJQ/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/8OIygIHpbzkXEnrFoak00Q/348s.jpg"
            },
        	# start of Houston restaurants
            {
                "id": "18",
                "restaurant_name": "Green Seed Vegan",
                "call": "+18325825566",
                "restaurant_phone": "(832) 582-5566",
                "address": "4320 Almeda Rd, Houston, TX 77004",
                "address_link": "https://www.google.com/maps/search/?api=1&query=Green+Seed+Vegan+Houston+TX",
                "rating": "4.0 ★★★★",
                "food_type": "Vegan",
                "price_range": "$$",
                "url" : "https://www.greenseedvegan.com/",
                "user_register_id" : "",
                "city": "Houston",
                "openingHours": [{"days": "MON - SUN", "hours": "11AM - 8PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/LrFZSorCjq6Cq9abzpkoWA/o.jpg",
                "img_2_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGHlwUMKjb8rkaWL87kGjYfCO3FADqaL8wwg&usqp=CAU",
                "img_3_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTp6THxiFkRdj0pfYCIJyyn7EnP-7gQFKR23g&usqp=CAU"
            },
            {
                "id": "19",
                "restaurant_name": "Veegos Vegan Eatery",
                "call": "+17134895323",
                "restaurant_phone": "(713) 489-5323",
                "address": "2435 Times Blvd, Houston, TX 77005",
                "address_link": "https://www.google.com/maps/search/?api=1&query=Veegos+Vegan+Eatery+Houston+TX",
                "rating": "4.5 ★★★★★",
                "food_type": "Vegan",
                "price_range": "$$",
                "url" : "https://www.veegoshouston.com/",
                "user_register_id" : "",
                "city": "Houston",
                "openingHours": [{"days": "MON - SAT", "hours": "11AM - 10PM"}, {"days": "SUN", "hours": "11AM - 7PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/xYVRcPFqLM9OA4k81LoY2w/348s.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/vt0m3EiEswq7QdAhhWKaDQ/348s.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/_ZOapDhhZ_t00mbJ9DrF6Q/348s.jpg"
            },
            {
                "id": "20",
                "restaurant_name": "Baby Yega Cafe",
                "call": "+17135220042",
                "restaurant_phone": "(713) 522-0042",
                "address": "2607 Grant St, Houston, TX 77006",
                "address_link": "https://www.google.com/maps/search/?api=1&query=Baba+Yega+Cafe+Houston+TX",
                "rating": "4.3 ★★★★",
                "food_type": "Vegan",
                "price_range": "$$",
                "url" : "http://babayega.com/",
                "user_register_id" : "",
                "city": "Houston",
                "openingHours": [{"days": "MON - SUN", "hours": "11AM - 8PM"}],
                "img_1_url": "https://www.oubruncher.com/photos1/4370_2.jpg",
                "img_2_url": "https://www.oubruncher.com/photos1/4370_3.jpg",
                "img_3_url": "https://pbs.twimg.com/media/Dr6LVYsX0AIOyK_.jpg"
            },
            {
                "id": "21",
                "restaurant_name": "Govinda's Vegetarian Cuisine",
                "call": "+18328319511",
                "restaurant_phone": "(832) 831-9511",
                "address": "1320 W 34th St, Houston, TX 77018",
                "address_link": "https://maps.app.goo.gl/ppmAAiqXKeciehPd7",
                "rating": "4.6 ★★★★★",
                "food_type": "Indian/ Vegetarian/ Vegan",
                "price_range": "$",
                "url" : "https://govindashou.com/",
                "user_register_id" : "",
                "city": "Houston",
                "openingHours": [{"days": "MON - SUN", "hours": "11AM - 2:30PM & 5PM - 9PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/u7fJldfIbq9u41YLeyErwg/o.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/GHJzKhj2PLI4hGQTvPaiJw/o.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/wPGk5R7-krGDfrL8wFsa3A/o.jpg"
            },
            {
                "id": "22",
                "restaurant_name": "Veegos",
                "call": "+12818885030",
                "restaurant_phone": "(281) 888-5030",
                "address": "10932 Westheimer Rd A, Houston, TX 77042",
                "address_link": "https://maps.app.goo.gl/t5hVGQs7KzH4kbJA9",
                "rating": "4.7 ★★★★★",
                "food_type": "Vegan",
                "price_range": "$",
                "url" : "https://www.veegoshouston.com/",
                "user_register_id" : "",
                "city": "Houston",
                "openingHours": [{"days": "MON - SAT", "hours": "11AM - 10PM"}, {"days": "SUN", "hours": "11AM - 7PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/wuMvFgvGFYra9_x_WhEilA/o.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/KG9KDV96sG8oMEuTJvAALA/o.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/EvLCWCgTNcAdqLJ6hMK52Q/o.jpg"
            },
            {
                "id": "23",
                "restaurant_name": "Trendy Vegan",
                "call": "+17136219488",
                "restaurant_phone": "(713) 621-9488",
                "address": "3821 Richmond Ave, Houston, TX 77027",
                "address_link": "https://maps.app.goo.gl/HxxGwX57Vt4bmcWw8",
                "rating": "4.6 ★★★★★",
                "food_type": "Vegan, Pan Asian, Buffets",
                "price_range": "$",
                "url" : "https://trendyhouston.com/",
                "user_register_id" : "",
                "city": "Houston",
                "openingHours": [{"days": "MON - SUN", "hours": "11AM - 8:45PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/iAgl8GrzdsBcu82l3m7c7A/o.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/eWYr0wjauanGxNqsEO4LfQ/o.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/AnPENYrF6tXOl5vL91wjIQ/o.jpg"
            },
            {
                "id": "24",
                "restaurant_name": "Field of Greens",
                "call": "+17135330029",
                "restaurant_phone": "(713) 533-0029",
                "address": "2320 W Alabama St, Houston, TX 77098",
                "address_link": "https://www.google.com/maps/search/?api=1&query=Field+of+Greens+Houston+TX",
                "rating": "3.8 ★★★★",
                "food_type": "Vegan",
                "price_range": "$$",
                "url" : "https://www.facebook.com/FieldofGreensVegan/",
                "user_register_id" : "",
                "city": "Houston",
                "openingHours": [{"days": "MON - THURS", "hours": "11AM - 9PM"}, {"days": "FRI - SAT", "hours": "11AM - 9:30PM"}, {"days": "SUN", "hours": "12PM - 5PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/9hJw_NC4OsaZZ2vOxvqXgw/o.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/zEdf6LwzswnXC_iMauWepg/o.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/nFR19N3mU4gNFjaz4AVR8g/o.jpg"
            },
            {
                "id": "25",
                "restaurant_name": "Soul Food Vegan",
                "call": "+18328212856",
                "restaurant_phone": "(832) 821-2856",
                "address": "2901 Emancipation Ave, Houston, TX 77004",
                "address_link": "https://www.google.com/maps/search/?api=1&query=Soul+Food+Vegan+Houston+TX",
                "rating": "3.5 ★★★★",
                "food_type": "Vegan",
                "price_range": "$$",
                "url" : "https://www.instagram.com/soul_food_vegan/",
                "user_register_id" : "",
                "city": "Houston",
                "openingHours": [{"days": "MON - SAT", "hours": "12PM - 8:30PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/4dOvByB-9I28VHUQzi9H-A/o.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/fRQHNKjfGfRvb62D60gPcA/o.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/v1HUfQXz3emn-a9m5ovjTA/o.jpg"
            },
            {
                "id": "26",
                "restaurant_name": "Pat Greer's Kitchen",
                "call": "+17138070101",
                "restaurant_phone": "(713) 807-0101",
                "address": "412 W Clay St, Houston, TX 77019",
                "address_link": "https://www.google.com/maps/search/?api=1&query=Pat+Greer%27s+Kitchen+Houston+TX",
                "rating": "4.6 ★★★★★",
                "food_type": "Vegan",
                "price_range": "$$",
                "url" : "https://www.patgreerskitchen.com/",
                "user_register_id" : "",
                "city": "Houston",
                "openingHours": [{"days": "TUES", "hours": "10AM - 3PM"}],
                "img_1_url": "https://s3-media0.fl.yelpcdn.com/bphoto/WO5ffACdQxtRYNV-TK0kZg/o.jpg",
                "img_2_url": "https://s3-media0.fl.yelpcdn.com/bphoto/-wDHHe8GWagC__GxHXFCGg/o.jpg",
                "img_3_url": "https://s3-media0.fl.yelpcdn.com/bphoto/tDvPPBTyDvyTyePa5Knz0w/o.jpg"
            }
        ]
        for restaurant in restaurant_list:
            opening_hours_json = json.dumps(restaurant['openingHours'])
            
            new_restaurant = Restaurant(
                id = restaurant['id'],
                restaurant_name = restaurant['restaurant_name'],
                call = restaurant['call'],
                restaurant_phone = restaurant['restaurant_phone'],
                address = restaurant['address'],
                address_link = restaurant['address_link'],
                rating = restaurant['rating'],
                food_type = restaurant['food_type'],
                price_range = restaurant.get('price_range', None),
                url = restaurant['url'],
                # user_register_id = restaurant['user_register_id'],
                city = restaurant['city'],
                openingHours=opening_hours_json,
                img_1_url = restaurant['img_1_url'],
                img_2_url = restaurant['img_2_url'],
                img_3_url = restaurant['img_3_url']
            )
            db.session.add(new_restaurant)
            db.session.commit()
            
			